# Generated by Django 5.0.6 on 2025-07-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wp_id', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_api.whatsappsession')),
            ],
        ),
    ]
