version: '3.8'

services:

  nginx_proxy_test:
    build:
      context: ./nginx_proxy
    volumes:
      - ./nginx_proxy/default.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx_proxy/certs:/etc/nginx/certs
    ports:
      - "10443:443"
    networks:
      manager_test:
        ipv4_address: 172.24.0.2 # ip to host
      coders_test:
        ipv4_address: 172.25.0.2

    environment:
      - IP_TO_HOST=172.24.0.2 # ip por la cual se expone el servicio
      - WEB_SERVER_IP=172.24.0.3 # ip del la pagina web

  portainer_test:
      image: portainer/portainer-ce
      container_name: portainer_test
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data_test:/data
      networks:
        manager_test:
          ipv4_address: 172.24.0.4

  web_test:
    build:
      context: ./project_manager
    volumes:
      - ./project_manager:/app
    depends_on:
      - nginx_proxy_test
      - portainer_test
    networks:
      manager_test:
        ipv4_address: 172.24.0.3
    environment:
      - PROXY_IP=172.24.0.2
      - PORTAINER_IP=172.24.0.4

# Red con los servicios principales
networks:
  manager_test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
# Red con los contenedores de vscode
  coders_test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  portainer_data_test: