# Generated by Django 5.0.6 on 2025-07-07 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('dockerId', models.CharField(max_length=100, unique=True)),
                ('imageId', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('ports', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortainerApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiToken', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExposePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_port', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('internal_port', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expose_ports', to='core.container')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.container')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exposeport',
            constraint=models.CheckConstraint(check=models.Q(('external_port__gte', 1), ('external_port__lte', 65535)), name='valid_external_port_range'),
        ),
        migrations.AddConstraint(
            model_name='exposeport',
            constraint=models.CheckConstraint(check=models.Q(('internal_port__gte', 1), ('internal_port__lte', 65535)), name='valid_internal_port_range'),
        ),
    ]
