# Generated by Django 5.0.6 on 2024-12-07 23:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expose_ports', to='core.container')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exposeport',
            constraint=models.CheckConstraint(check=models.Q(('port__gte', 1), ('port__lte', 65535)), name='valid_port_range'),
        ),
    ]
