# Generated by Django 5.0.6 on 2024-12-08 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exposeport_exposeport_valid_port_range'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exposeport',
            name='valid_port_range',
        ),
        migrations.RenameField(
            model_name='exposeport',
            old_name='port',
            new_name='external_port',
        ),
        migrations.AddField(
            model_name='exposeport',
            name='internal_port',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddConstraint(
            model_name='exposeport',
            constraint=models.CheckConstraint(check=models.Q(('external_port__gte', 1), ('external_port__lte', 65535)), name='valid_external_port_range'),
        ),
        migrations.AddConstraint(
            model_name='exposeport',
            constraint=models.CheckConstraint(check=models.Q(('internal_port__gte', 1), ('internal_port__lte', 65535)), name='valid_internal_port_range'),
        ),
    ]
