# Generated by Django 5.0.6 on 2024-12-08 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_exposeport_valid_port_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposeport',
            name='internal_port',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
