# Generated by Django 5.0.6 on 2025-07-07 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortainerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token de acceso generado por Portainer', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Usuario al que pertenece el token de Portainer', on_delete=django.db.models.deletion.CASCADE, related_name='portainer_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
